[package]
name = "durnitisp"
version = "0.1.0"
authors = ["Jeremy Wall <jeremy@marzhillstudios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
gflags = "^0.3"
log = "0.4"
nursery = "^0.0.1"
prometheus = "^0.9.0"
stderrlog = "0.4"
tiny_http = "^0.7.0"
ekko = { git = "https://github.com/dev-bio/Ekko", branch = "ipv-hops"}
resolve = "^0.2.0"